services:
  app:
    image: ghcr.io/vachagunn/scenarist-tools:main
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_DB}"
      APP_DOMAIN: $APP_DOMAIN
      APP_URL: $APP_URL
      APP_INTERNAL_KEY: $APP_INTERNAL_KEY
      # NODE_ENV: $NODE_ENV
      SSO_GOOGLE_CLIENT_ID: $SSO_GOOGLE_CLIENT_ID
      SSO_GOOGLE_CLIENT_SECRET: $SSO_GOOGLE_CLIENT_SECRET
      SESSION_SECRET: $SESSION_SECRET
      SESSION_TTL: $SESSION_TTL

  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_DB}"
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
